services:
  cs2_modded_server:
    image: cs2-modded-server
    container_name: cs2-modded-server
    env_file:
      - .env
    volumes:
      - ./steamcmd:/steamcmd
      - ./steam:/home/steam/
      - ./game:/home/game/
      - ./custom_files:/home/custom_files/
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/tcp"
      - "27020:27020/udp"
    cpu_count: 2
    mem_limit: 3500m
    # command: tail -F anything